export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

//Temperature actions types
export const RECEIVED_AVG_TEMP_PER_SEMAINE = 'RECEIVED_AVG_TEMP_PER_SEMAINE';
export const RECEIVED_AVG_TEMP_AUJOURDHUI = 'RECEIVED_AVG_TEMP_AUJOURDHUI';
export const RECEIVED_AVG_TEMP_PER_ANNEE = 'RECEIVED_AVG_TEMP_PER_ANNEE';
export const REQUEST_TEMP_FAILED = 'REQUEST_TEMP_FAILED';

//Pluvio actions Types
export const RECEIVED_AVG_PLUVIO_PER_ANNEE = 'RECEIVED_AVG_PLUVIO_PER_ANNEE';
export const RECEIVED_AVG_PLUVIO_PER_SEMAINE = 'RECEIVED_AVG_PLUVIO_PER_SEMAINE';
export const RECEIVED_AVG_PLUVIO_AUJOURDHUI = 'RECEIVED_AVG_PLUVIO_AUJOURDHUI';
export const REQUEST_PLUVIO_FAILED = 'REQUEST_PLUVIO_FAILED';

//WindSpeed actions Types
export const RECEIVED_AVG_WINDSPEED_PER_ANNEE = 'RECEIVED_AVG_WINDSPEED_PER_ANNEE';
export const RECEIVED_AVG_WINDSPEED_PER_SEMAINE = 'RECEIVED_AVG_WINDSPEED_PER_SEMAINE';
export const RECEIVED_AVG_WINDSPEED_MOIS = 'RECEIVED_AVG_WINDSPEED_MOIS';
export const REQUEST_WINDSPEED_FAILED = 'REQUEST_WINDSPEED_FAILED';